name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "109ded07f8be1d27acfa8dad11b50848648015a0f8d3e2c7c8f2b88e536b0a81"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
