name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73ddb3a33653aae99169f93d58aacd7331c2f9954150f6a97f0f063d5ddf567b"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
