name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa14ed57458101086ec43dc0c1044c45a31a37f43248a1e20c9d44c5c767e14"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
